### ISSUE TITLE
Connection Timeout on Sync Gradle for 'play-services-analytics-impl'

### ISSUE THREAD

**Issue by canuludag** [synergian/wagon-git#51]
I'm getting connection timeout (503) when I try to sync gradle. Full error message is this:
`Could not GET 'https://raw.github.com/synergian/wagon-git/releases/com/google/android/gms/play-services-analytics-impl/'. Received status code 503 from server: Connection timed out`

How can I resolve this? It started today.

**Comment by mschonaker** [comment]
It looks like GitHub is responding with 503 instead of 400 for non-existent
resources.

A quick solution could be making the repository containing that artifact
(com/google/android/gms/play-services-analytics-impl/) to have precedence
over wagon-git's.

A long term solution could be something like moving this repo to GitLab.

**Comment by canuludag** [comment]
Yeah could be. Error occurred temporarily and now it's gone.
